server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/dvdrental
    username: shhan
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

  # 해당 옵션을 풀면 에러가 발생한다.
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    root: info


