server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/dvdrental
    username: shhan
    password: 1234
  jackson:
    serialization:
      fail-on-empty-beans: false


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    root: info

